### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by unickorn** [RobLoach/ubuntu-mate#1]
The resolution seems to be incorrect for me and I want to uninstall it. How would I do that?

**Comment by RobLoach** [comment]
GRUB Customizer will do it:
https://launchpad.net/~danielrichter2007/+archive/ubuntu/grub-customizer

In the customizer, you can change the resolution manually, or other properties about the theme.

**Comment by RobLoach** [comment]
http://tipsonubuntu.com/2018/03/11/install-grub-customizer-ubuntu-18-04-lts/
