### ISSUE TITLE
Manjaro has the gnu-linux icon

### ISSUE THREAD

**Issue by mccoys** [RobLoach/ubuntu-mate#3]
On a dual-boot with Manjaro, the icon is that of gnu-linux instead of the Manjaro icon available in the list.

**Comment by RobLoach** [comment]
Good catch! I think it should be this one?
https://github.com/shvchk/poly-light/blob/master/icons/gnu-linux.png

**Comment by mccoys** [comment]
Maybe I was not so clear ;)

The manjaro icon does not seem to be recognized by grub. So it switches automatically to the fallback `gnu-linux.png`.

However, after looking for this bug, I am thinking it may not be related to your theme. It seems to be happening to all themes ...

**Comment by RobLoach** [comment]
Would be good to fix it up!

Maybe one of these?
https://forum.manjaro.org/t/appmenu-whiskermenu-icons/21759

Are you a good icon editor? I'm no designer hhaha.

**Comment by mccoys** [comment]
The problem is that I don't know how to fix the problem

**Comment by RobLoach** [comment]
It's this image:
https://github.com/RobLoach/ubuntu-mate/blob/master/icons/manjaro.png

Likely a corrupt png or something. May need a re-export?

**Comment by mccoys** [comment]
The issue is not the image !
Instead, it is due to grub not recognizing it.

I realized that the issue is not in your theme. It happens for all themes.
Sorry for the mistake

**Comment by RobLoach** [comment]
No worries! I brought the latest icons down from poly-light. Saw a few updates come through.
